# Project data extracted from the old Next.js codebase (lib/projects.ts + each project page.tsx),
# consolidated into one source of truth for the static-site generator.
#
# Adding a project
# ---------------
# Append a dict below and run `python _build/build_site.py`. Nothing else is
# wired by hand: the page, the slate card, the work-page grouping, the sitemap
# entry, the share card and the JSON-LD all come off this record.
#
#   active        the only switch that matters. True builds the page and puts
#                 the project in the sitemap; False removes both, and the build
#                 deletes the page it left behind.
#   slate         show it on the homepage slate strip (first six).
#   featured      the single large card on the homepage. One project only.
#   image         hero. Required. 16:9 or wider; the page title sits bottom
#                 left, so keep the subject out of that corner.
#   hero_focus    optional object-position, e.g. "20% top", when the phone crop
#                 would otherwise lose the subject.
#   gallery       list of {src, w, h, alt}. w/h are the real pixel size - the
#                 stills carry their own shapes rather than a shared crop.
#   frame         optional frame number a still was pulled at. Give them and the
#                 build enforces screen order; the filename prefix carries the
#                 sequence, but the number is what proves it.
#   gallery_ratio optional "w/h" for the grid and carousel cells. Left out, the
#                 build uses the commonest shape in the array, so a set that is
#                 all one aspect just works. Cells are uniform on purpose - the
#                 grid is a contact sheet, and a ragged row reads as a mistake;
#                 the full frame is still what opens in the viewer.
#   show_gallery  False keeps a planned shot list in the data without rendering
#                 it. Turning it True requires every file to exist; the build
#                 refuses to run otherwise rather than shipping broken images.
#   nominations   list of {org, years}; the badge counts all of them, the
#                 project page lists only the TIER1_ORGS ones.
#   credit        only for produced work, where the imagery is frames from the
#                 finished film.

PROJECTS = [
    {
        "slug": "family-tradition",
        "title": "Family Tradition",
        "format": "short", "genre": "Short Film — Southern Gothic / Drama",
        "status": "Post-Production",
        "zinger": "Family ain’t what you inherit—it’s what you survive.",
        "overview": "On a storm-soaked night in a dying Southern town, three estranged siblings reunite at a diner after their father’s funeral, hoping to put the past behind them. Instead, old wounds split open as buried truths about their family begin to surface—rumors of murder, secrets about their mother, and the dark legacy tied to their land. As tensions rise, one brother reveals he may be more like their father than anyone wants to admit. What starts as a conversation turns into a reckoning, as the line between victim and monster blurs beyond recognition. When the past finally walks through the door, it becomes clear—this family’s story was never over.",
        "image": "/images/family-tradition/ft-gray-diner.webp",  # frame 88318
        # The hero is a wide frame in a tall mobile box, so object-cover keeps
        # only the middle ~42% of it. Gray sits at 26% across, which that window
        # misses entirely. Anchoring at 20% keeps him in shot on a phone.
        "hero_focus": "20% top",
        "subtitle": "In this family, inheritance doesn’t come with money—it comes with blood.",
        "teaser": "There’s things in this town much worse than murder.",
        "teaser_speaker": "Gray Harris",
        "themes": ["Identity", "Family Legacy", "Inherited Violence", "Truth vs Denial"],
        "tone": "Contained tension. Intimate. Volatile. Darkly human.",
        "comps": "The Hateful Eight meets August: Osage County",
        "nominations": [],
        # Imagery on this page is frames from the finished film; credited, not disclaimed.
        "credit": ["dir. Bailey Donovan", "DP Kristian Dane Lawing"],
        "show_gallery": True,
        # Frames from the colour-corrected master. w/h are the real pixel
        # dimensions - the matte opens from 2.67:1 to 16:9 across the film,
        # so each still carries its own shape rather than a shared crop.
        # Screen order, first frame to last. The ft-NN prefix carries the
        # sequence, so the order survives a rename or a re-export.
        # Screen order, first frame of the film to last. "frame" is the frame
        # number the still was pulled at; the build refuses to run if an array
        # carrying them is out of order, so the sequence cannot drift again.
        "gallery": [
            {"src": "/images/family-tradition/stills/ft-01-car-night.webp", "w": 1600, "h": 635, "frame": 87742,
             "alt": "A man sits alone behind the wheel of a parked car, lit red from outside"},
            {"src": "/images/family-tradition/stills/ft-02-counter-night.webp", "w": 1600, "h": 600, "frame": 88512,
             "alt": "A waitress leans across the counter of an empty diner late at night"},
            {"src": "/images/family-tradition/stills/ft-03-cook-pass.webp", "w": 1600, "h": 600, "frame": 88551,
             "alt": "A cook in a white apron framed through the kitchen pass of a diner"},
            {"src": "/images/family-tradition/stills/ft-04-purple-standing.webp", "w": 1600, "h": 600, "frame": 91084,
             "alt": "A woman in a purple coat stands over a booth mid-sentence"},
            {"src": "/images/family-tradition/stills/ft-05-two-shot.webp", "w": 1600, "h": 600, "frame": 92082,
             "alt": "A young woman looks off past a man\u2019s shoulder in a dim diner booth"},
            {"src": "/images/family-tradition/stills/ft-06-gingham-react.webp", "w": 1600, "h": 600, "frame": 94905,
             "alt": "A waitress in a red gingham top reacts to something across the diner"},
            {"src": "/images/family-tradition/stills/ft-07-tomato.webp", "w": 1600, "h": 600, "frame": 95305,
             "alt": "A man holds up a slice of tomato beside a young woman in a booth"},
            {"src": "/images/family-tradition/stills/ft-08-booth-purple.webp", "w": 1600, "h": 600, "frame": 95341,
             "alt": "A woman in a purple fur coat and a man in a suit sit together in a diner booth"},
            {"src": "/images/family-tradition/stills/ft-09-jolene-wade.webp", "w": 1600, "h": 600, "frame": 99790,
             "alt": "A man in a suit talks close to a woman with long curled hair"},
            {"src": "/images/family-tradition/stills/ft-10-ranger-counter.webp", "w": 1600, "h": 644, "frame": 101500,
             "alt": "A park ranger leans on the counter talking to a waitress, gold records on the wall behind"},
            {"src": "/images/family-tradition/stills/ft-11-diner-wide.webp", "w": 1600, "h": 600, "frame": 102207,
             "alt": "A ranger stands at the door of a near-empty diner, seen past a woman in the foreground"},
            {"src": "/images/family-tradition/stills/ft-12-shovel.webp", "w": 1600, "h": 600, "frame": 103390,
             "alt": "A man raises a long-handled tool, seen from below against bare winter branches"},
            {"src": "/images/family-tradition/stills/ft-13-knife-carve.webp", "w": 1600, "h": 845, "frame": 103542,
             "alt": "A hand carves a mark into pine bark with a pocket knife as sap runs down"},
            {"src": "/images/family-tradition/stills/ft-14-harlan.webp", "w": 1600, "h": 900, "frame": 106168,
             "alt": "An older bearded man in a cap, lit deep red, staring ahead"},
        ],
        "active": True, "slate": False, "featured": True,
    },
    {
        "slug": "the-last-stop",
        "title": "The Last Stop",
        "format": "short", "genre": "Animated Short — Magical / Drama",
        "status": "Post-Production",
        "zinger": "He thought he was ready to die—until life gave him one more reason to stay.",
        "overview": "On the day he plans to end his life, a widowed old man sets his affairs in order and heads toward what he believes will be his final destination. Along the way, small, unexpected encounters begin to crack open something he thought was long gone—purpose. What starts as a routine goodbye turns into a quiet reckoning with grief, memory, and the life he’s been running from. When he arrives at a surreal bus terminal between life and death, he’s forced to confront a simple but impossible question: is he truly ready to let go? In a place where every soul must choose, the answer may not be what he expected.",
        "image": "/images/last-stop/last-stop-station.webp",
        "subtitle": "At the end of the line, the hardest choice isn’t dying—it’s deciding if you’re done living.",
        "teaser": "To do—or to die.",
        "teaser_speaker": "Death",
        "themes": ["Grief", "Purpose", "Choice", "Letting Go"],
        "tone": "Bittersweet. Reflective. Magical realism. Quietly hopeful.",
        "comps": "Soul meets The Sixth Sense",
        "nominations": [],
        # Imagery on this page is frames from the finished film; credited, not disclaimed.
        "credit": ["dir. Timea Shuman", "animation by Clemhyn Escosora of Adarnia Studio"],
        "show_gallery": True,
        "gallery": [
            {"src": "/images/last-stop/last-stop-slugger.webp", "w": 1400, "h": 592, "alt": "An animated young man in a batting helmet rests a bat on his shoulder"},
            {"src": "/images/last-stop/last-stop-ready.webp", "w": 1400, "h": 592, "alt": "An elderly animated man in a bow tie stands in a doorway facing another man"},
            {"src": "/images/last-stop/last-stop-dogs.webp", "w": 1400, "h": 591, "alt": "An elderly animated man walks two white dogs along a small-town street"},
            {"src": "/images/last-stop/last-stop-phone.webp", "w": 1400, "h": 592, "alt": "An elderly animated man holds a phone to his ear on a sunlit street corner"},
            {"src": "/images/last-stop/last-stop-boy.webp", "w": 1400, "h": 592, "alt": "An animated boy in a green jacket stands beside a garden pond, looking at his hands"},
            {"src": "/images/last-stop/last-stop-car.webp", "w": 1400, "h": 591, "alt": "A smiling animated young man in a flat cap in a car, an action figure held up in front of him"},
            {"src": "/images/last-stop/last-stop-sitter.webp", "w": 1400, "h": 590, "alt": "A red-haired animated young woman turns as a hand holds out a set of keys"},
            {"src": "/images/last-stop/last-stop-david.webp", "w": 1400, "h": 591, "alt": "An elderly animated man with glasses holds a baseball, warmly lit"},
        ],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "sunsets-in-memphis",
        "title": "Sunsets In Memphis",
        "format": "short", "genre": "Animated Short — Sci-Fi / Adventure / Comedy",
        "status": "In Development",
        "zinger": "A lone gunslinger in space is forced to trust the one man too useless to survive—until he saves everything.",
        "overview": "After a mission goes catastrophically wrong, a hardened space operative crash-lands on a distant world with nothing but her dog and a deeply unqualified partner she never wanted. Stranded in a strange and hostile environment, she’s forced to rely on a man whose awkward logic and strange way of seeing the world clashes with everything she knows about survival. When they stumble upon a hidden force tied to the very enemy she’s been hunting, the mission shifts from revenge to something far more unexpected. As tension gives way to unlikely trust, she’s forced to confront the possibility that strength doesn’t always look the way she thought it did. In a universe built on violence, the solution might come from the last place she’d ever look.",
        "image": "/images/sunsets-in-memphis/sunsets-hero.webp",
        "hero_source": "/images/sunsets-in-memphis/sunsets.jpeg",
        "subtitle": "Sometimes the person you least believe in is the only one who can change everything.",
        "teaser": "Guess you’re not useless after all.",
        "teaser_speaker": "Vera Thorn",
        "themes": ["Trust", "Perception Vs. Reality", "Connection", "Purpose"],
        "tone": "Offbeat. Character-driven. Sci-fi adventure with humor.",
        "comps": "Guardians of the Galaxy meets Firefly",
        "nominations": [],
        "show_gallery": False,
        "gallery": [],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "wilder",
        "title": "Wilder",
        "format": "feature", "genre": "Feature — Southern Drama",
        "status": "In Development",
        "zinger": "She lied her way into his story—now it’s the only thing that can save her life.",
        "overview": "In 1984 Mississippi, a struggling single mother impersonates a journalist to land a career-making interview with a reclusive racing legend on the verge of retirement. Desperate to prove she’s more than the life she’s been handed, she crosses a line that could cost her everything—her children, her future, and her sense of self. As she earns the trust of a man haunted by his own past, their connection begins to blur the line between truth and performance. What starts as a con becomes something real, forcing them both to confront the cost of the lives they’ve lived and the ones they still might choose. When the truth finally catches up, she must decide if she’s willing to lose it all to finally become someone worth believing in.",
        "image": "/images/wilder/wilder-hero.webp",
        "hero_source": "/images/wilder/wilder.jpeg",
        "subtitle": "To become who she’s meant to be, she has to risk losing everything she’s pretending to be.",
        "teaser": "Until you make the unconscious conscious, it’ll direct your life—and you’ll call it fate.",
        "teaser_speaker": "Sophie Waters",
        "themes": ["Identity", "Reinvention", "Truth Vs. Performance", "Redemption"],
        "tone": "Character-driven. Gritty. Hopeful. Southern.",
        "comps": "Erin Brockovich meets Crazy Heart",
        "nominations": [
            {"org": "Austin Film Festival", "years": [2025], "placement": "Second Rounder - Drama Feature"},
            {"org": "Los Angeles International Screenwriting Awards", "years": [2025], "placement": "Semifinalist - Fall 2025"},
            {"org": "Filmmatic Drama Screenplay Awards", "years": [2025], "placement": "Quarterfinalist - Season 10"},
            {"org": "Stage 32", "years": [2026], "placement": "Finalist - Open Writing Assignment #0615"},
        ],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/wilder/courtroom.webp"},
            {"src": "/images/wilder/leaving.webp"},
            {"src": "/images/wilder/payphone.webp"},
            {"src": "/images/wilder/retirement-speech.webp"},
            {"src": "/images/wilder/the-meeting.webp"},
            {"src": "/images/wilder/hotdogs.webp"},
        ],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "dupree",
        "title": "Who Stole the Head of Bobbi DuPree",
        "format": "feature", "genre": "Feature — Western / Adventure",
        "status": "In Development",
        "zinger": "A severed head holds the map to a fortune—now every killer in the territory wants it.",
        "overview": "In 1876 Indian Territory, the notorious outlaw Bobbi DuPree is beheaded—his wooden eye rumored to contain the secret location of millions in stolen Confederate gold. As word spreads, a ruthless bounty is placed on his severed head, igniting a violent race across the frontier. A reluctant bounty hunter with a spotless reputation and a fast-talking Confederate drifter form an uneasy alliance, chasing the prize while being hunted themselves. But they’re not alone. A deadly pair of sadistic twins, a zealot priest who kills in God’s name, and a growing army of mercenaries all close in—each more dangerous than the last. As alliances shift and bodies pile up, the hunt becomes less about the gold and more about survival. Because in a land ruled by myth, violence, and greed, the real question isn’t who finds the treasure—it’s who lives long enough to keep it.",
        "image": "/images/dupree/dupree-hero.webp",
        "hero_source": "/images/dupree/dupree.jpeg",
        "subtitle": "Greed doesn’t just corrupt men—it reveals who they were all along.",
        "teaser": "My name is Bobbi DuPree—and this is how I lost my head.",
        "teaser_speaker": "Bobbi DuPree",
        "themes": ["Greed", "Myth Vs. Reality", "Survival", "Fate Vs. Choice"],
        "tone": "Violent. Darkly humorous. Mythic. Grit-soaked.",
        "comps": "No Country for Old Men meets The Hateful Eight",
        "nominations": [
            {"org": "Nashville Film Festival", "years": [2026], "placement": "Semifinalist - Genre Feature"},
            {"org": "HollyShorts Film Festival", "years": [2026], "placement": "Quarterfinalist"},
            {"org": "ISA / Script Pipeline Great Pitch Competition", "years": [2025], "placement": "Semifinalist"},
            {"org": "ISA Top Reads", "years": [2026], "placement": "Top Reads Selection - Summer 2026"},
        ],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/dupree/headless.webp"},
            {"src": "/images/dupree/sly.webp"},
            {"src": "/images/dupree/rimes.webp"},
            {"src": "/images/dupree/rimes-being-rimes.webp"},
            {"src": "/images/dupree/mary-lou.webp"},
            {"src": "/images/dupree/the-taker.webp"},
            {"src": "/images/dupree/three-limbed-tree.webp"},
            {"src": "/images/dupree/trouble.webp"},
        ],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "pines",
        "title": "What’s Buried Beneath the Pines",
        "format": "tv", "genre": "Pilot — Southern Gothic / Crime / Drama",
        "status": "In Development",
        "zinger": "Some families pass down land. His passed down bodies.",
        "overview": "When Gray Harris returns to his rural Georgia hometown after his estranged father’s brutal death, he inherits a crumbling timber business and a legacy built on secrets. What looks like a suicide quickly unravels into something far darker, as missing evidence, local rumors, and quiet threats begin to close in around him. As pressure mounts to sell the land, Gray realizes powerful people are willing to hurt his family to get it. Forced back into a past he ran from, he and his siblings must confront the truth about their parents, their town, and the violence buried beneath it all. The deeper Gray digs, the clearer it becomes—this isn’t just history. It’s still alive.",
        "image": "/images/pines/pines-hero.webp",
        "hero_source": "/images/pines/pines.jpeg",
        "hero_size": (2000, 1125),
        "subtitle": "Some families don’t pass down land. They pass down what’s buried beneath it.",
        "teaser": "There’s an awful lot of secrets buried beneath the pines.",
        "teaser_speaker": "Gray Harris",
        "themes": ["Identity", "Family Legacy", "Buried Truth", "Moral Consequence"],
        "tone": "Slow-burn tension. Grounded. Intimate. Uneasy.",
        "comps": "Ozark meets Succession",
        "nominations": [
            {"org": "Nashville Film Festival", "years": [2025, 2026], "placement": "Finalist 2025 (One-Hour Pilot); Semifinalist 2026 (60-Minute Pilot)"},
            {"org": "Script Pipeline", "years": [2025], "placement": "Semifinalist - TV Writing Contest"},
            {"org": "Austin Film Festival", "years": [2025], "placement": "Second Rounder - One-Hour Pilot"},
            {"org": "HollyShorts Film Festival", "years": [2026], "placement": "Quarterfinalist"},
            {"org": "PAGE International Screenwriting Awards", "years": [2025], "placement": "Quarterfinalist"},
            {"org": "Final Draft Big Break", "years": [2025], "placement": "Quarterfinalist"},
            {"org": "Filmmatic InRoads Fellowship", "years": [2025], "placement": "Semifinalist - Season 8"},
            {"org": "Filmmatic TV Pilot Awards", "years": [2025], "placement": "Semifinalist - Season 10"},
            {"org": "Los Angeles International Screenwriting Awards", "years": [2025], "placement": "Semifinalist - Fall 2025"},
            {"org": "Outstanding Screenplays TV Pilot Competition", "years": [2025], "placement": "Quarterfinalist"},
            {"org": "Roadmap Writers JumpStart", "years": [2025], "placement": "Top 50 / Quarterfinalist - Pilot"},
            {"org": "Stage 32", "years": [2025], "placement": "Selected - Open Writing Assignment #0440"},
            {"org": "ISA Fast Track Fellowship", "years": [2026], "placement": "Second Round Selection - Spring 2026"},
            {"org": "CineStory TV Contest", "years": [2026], "placement": "Quarterfinalist"},
        ],
        # Not contest placements, so deliberately excluded from the count.
        "evaluations": [
            {"org": "The Black List", "result": "Overall evaluation: 6"},
            {"org": "WeScreenplay", "result": "96th percentile evaluation"},
        ],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/pines/burial.webp"},
            {"src": "/images/pines/harlans-truck.webp"},
            {"src": "/images/pines/harris-timber.webp"},
            {"src": "/images/pines/crime-scene.webp"},
            {"src": "/images/pines/dutiful-daughter.webp"},
            {"src": "/images/pines/prodigal-son.webp"},
            {"src": "/images/pines/buddy.webp"},
            {"src": "/images/pines/fire.webp"},
        ],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "lords-of-franklin-county",
        "title": "Lords of Franklin County",
        "format": "tv", "genre": "Pilot — Southern Crime / Drama / Period",
        "status": "In Development",
        "zinger": "When the law robs the poor, an outlaw gives it back.",
        "overview": "In Depression-era Franklin County, a war-scarred drifter returns home to find his land stolen, his town controlled, and its people crushed under the thumb of a corrupt judge and ruthless sheriff. With nothing left to lose, he assembles a ragtag crew—a preacher with a moral code, a giant with a gentle heart, and a reckless young outlaw—and begins stealing from the wealthy elite who profit off the suffering of others. As their legend grows, so does the danger. The law closes in. Loyalties fracture. And the line between justice and revenge begins to blur. Because in a town where the system is broken, the question isn’t who’s right—it’s who’s willing to do something about it.",
        "image": "/images/lords/lords-hero.webp",
        "hero_source": "/images/lords/lords.jpeg",
        "hero_size": (2000, 1125),
        "subtitle": "Justice isn’t always lawful—and sometimes doing right means becoming the thing you hate.",
        "teaser": "They were free… until a man with a rifle came along and took it from ’em.",
        "teaser_speaker": "Finch Crawford",
        "themes": ["Justice Vs. Revenge", "Faith Vs. Action", "Power and Corruption", "Found Family"],
        "tone": "Gritty. Emotional. Character-first. Humor. Myth-building.",
        "comps": "Peaky Blinders meets Justified",
        "nominations": [
            {"org": "Nashville Film Festival", "years": [2026], "placement": "Quarterfinalist - 60-Minute Pilot"},
        ],
        "show_gallery": False,
        "gallery": [],
        "active": True, "slate": True, "featured": False,
    },
    {
        "slug": "my-life-before-me",
        "title": "My Life Before Me",
        "format": "tv", "genre": "Half-Hour — Supernatural / Comedy",
        "status": "Early Development",
        "zinger": "He died a disaster—now he has to fix every life he ruined before he gets erased.",
        "overview": "After a drunken accident kills him, a washed-up piano prodigy wakes up in the afterlife—only to learn he’s not headed to heaven or hell, but something far worse: accountability. Forced into a bizarre cosmic system run by a rogue stand-in for Death, he’s sent back to Earth to inhabit the bodies of people whose lives he destroyed and fix them from the inside out. There are rules: don’t make things worse, don’t reveal who he is, and never contact anyone from his old life. Naturally, he breaks them almost immediately. As he jumps from life to life—each messier than the last—he’s forced to confront the consequences of who he used to be, while navigating a surreal system that may be just as broken as he is. Because if he fails, he won’t go to hell—he’ll be erased entirely.",
        "image": "/images/my-life-before-me/my-life-before-me-hero.webp",
        "hero_source": "/images/my-life-before-me/my_life_before_me.jpeg",
        "subtitle": "Redemption isn’t about getting your life back—it’s about fixing the damage you left behind.",
        "teaser": "You messed up. A lot. And we’re going to make it all better.",
        "teaser_speaker": "David",
        "themes": ["Redemption", "Consequences", "Identity", "Second Chances"],
        "tone": "Irreverent. Fast-paced. Existential. Darkly funny.",
        "comps": "The Good Place meets Quantum Leap",
        "nominations": [],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/my-life-before-me/a-time.webp"},
            {"src": "/images/my-life-before-me/hard-to-remember.webp"},
            {"src": "/images/my-life-before-me/david.webp"},
            {"src": "/images/my-life-before-me/afterlife.webp"},
            {"src": "/images/my-life-before-me/council.webp"},
            {"src": "/images/my-life-before-me/rules.webp"},
            {"src": "/images/my-life-before-me/inhabit.webp"},
            {"src": "/images/my-life-before-me/lumina-and-chronos.webp"},
        ],
        "active": True, "slate": False, "featured": False,
    },
    {
        "slug": "nothing-changes",
        "title": "Nothing Changes",
        "format": "feature", "genre": "Feature — Drama",
        "status": "Early Development",
        "zinger": "He kept trying to escape his life—until he realized he was the one he couldn’t outrun.",
        "overview": "A homeless addict drifts through a cycle of self-destruction, chasing relief that never lasts and control he never truly has. As memories of childhood love and trauma collide with the brutal reality of addiction, his world tightens into a pattern he can’t break—no matter how many times he survives it. Even death doesn’t offer escape, as each attempt to start over leads him back to the same place, the same pain, the same choices. When he finally hits a point where nothing works—not drugs, not running, not even dying—he’s forced to confront the one thing he’s avoided his entire life: himself. Because the truth isn’t that nothing changes—it’s that nothing changes until you do.",
        "image": "/images/nothing-changes/nothing-changes.webp",
        "subtitle": "You don’t get better by surviving—you get better when you finally stop running.",
        "teaser": "I wasn’t trying to get high… I was trying to feel okay being me.",
        "teaser_speaker": "Kris S.",
        "themes": ["Identity", "Addiction", "Shame", "Acceptance"],
        "tone": "Raw. Intimate. Unflinching. Grounded.",
        "comps": "Requiem for a Dream meets Sound of Metal",
        "nominations": [],
        "show_gallery": False,
        "gallery": [],
        "active": False, "slate": False, "featured": False,
    },
    {
        "slug": "dead-in-the-water",
        "title": "Dead in the Water",
        "format": "tv", "genre": "Pilot — Southern Gothic / Crime / Drama",
        "status": "Early Development",
        "zinger": "Bodies surface in the water—proof that something buried in this town is still alive.",
        "overview": "A recovering detective in rural Georgia is pulled into a disturbing case when a child’s bracelet is found inside the stomach of a black bear—seemingly random, until it connects to a missing girl. What begins as an isolated investigation quickly expands as more bodies surface along the state’s waterways, each one placed with deliberate intent. As jurisdictional lines blur, the theory of a lone killer gives way to something far more dangerous: a hidden network operating across communities, bound by a shared belief in purification through violence. While leading the investigation, he’s forced to navigate the same town that once covered up his own past, raising a chilling possibility—this system isn’t outside the community, it is the community. As symbols, rituals, and patterns begin to reveal themselves, the case stops being about who did it—and becomes about how deep it goes. Because by the time he understands what he’s facing, he may already be surrounded by it.",
        "image": "/images/dead-in-the-water/dead-in-the-water-hero.webp",
        "hero_source": "/images/dead-in-the-water/dead_in_the_water.jpeg",
        "subtitle": "The deeper he digs into the truth, the more it looks like the people he trusts are part of it.",
        "teaser": "People call it cleansing. I call it what it is—murder with a Bible wrapped around it.",
        "teaser_speaker": "Church Mitchell",
        "themes": ["Redemption", "Faith Vs. Corruption", "Truth Beneath Community", "Control"],
        "tone": "Atmospheric. Slow-burn. Investigative. Unsettling.",
        "comps": "True Detective meets Mare of Easttown",
        "nominations": [],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/dead-in-the-water/crime.webp"},
            {"src": "/images/dead-in-the-water/bracelet.webp"},
            {"src": "/images/dead-in-the-water/messy.webp"},
            {"src": "/images/dead-in-the-water/church.webp"},
            {"src": "/images/dead-in-the-water/evidence.webp"},
            {"src": "/images/dead-in-the-water/cute-but-weird.webp"},
            {"src": "/images/dead-in-the-water/river.webp"},
            {"src": "/images/dead-in-the-water/another-one.webp"},
        ],
        "active": True, "slate": False, "featured": False,
    },
    {
        "slug": "ballad-of-colibri",
        "title": "The Ballad of Colibri",
        "format": "feature", "genre": "Animated Feature — Adventure / Coming-of-Age",
        "status": "Early Development",
        "zinger": "A reckless young hummingbird chases fame—only to learn the magic he’s looking for might cost him everything.",
        "overview": "In a retro-styled desert city run by predatory financiers, a rebellious young hummingbird dreams of escaping his struggling family circus to become a legendary musician. After a disastrous mistake helps destroy everything his father built, he leaves home chasing a rumor of mystical power hidden deep in the Appalachian mountains—something said to grant any bird the talent they lack. Along the way, he falls in with a group of chaotic misfits and begins to believe the myth might be real. But as the journey grows more dangerous and the line between destiny and illusion blurs, he’s forced to confront a harder truth: the thing holding him back isn’t the world—it’s himself. When the cost of greatness becomes clear, he must decide what matters more—being famous, or being whole.",
        "image": "/images/colibri/selfie.webp",
        "subtitle": "To become who he’s meant to be, he has to stop running from where he came from.",
        "teaser": "I’m not staying here to be nobody—I’m leaving to be something.",
        "teaser_speaker": "Colibri",
        "themes": ["Identity", "Belonging", "Ambition Vs. Responsibility", "Self-Worth"],
        "tone": "Energetic. Musical. Irreverent. Heartfelt.",
        "comps": "Across the Spider-Verse meets Walk the Line",
        "nominations": [],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/colibri/bankrupt.webp"},
            {"src": "/images/colibri/magda.webp"},
            {"src": "/images/colibri/fire.webp"},
            {"src": "/images/colibri/thrashville.webp"},
            {"src": "/images/colibri/band.webp"},
            {"src": "/images/colibri/awaits.webp"},
        ],
        "active": False, "slate": False, "featured": False,
    },
    {
        "slug": "losers-guide",
        "title": "The Loser’s Guide to Surviving the Apocalypse",
        "format": "feature", "genre": "Feature — Post-Apocalyptic Dramedy / Horror",
        "status": "Early Development",
        "zinger": "He spent his whole life invisible—now everyone still alive is following his rules.",
        "overview": "Fifteen years after the world fell to the dark-dwelling things survivors call Vamps, Nicole Wells walks away from a failing settlement carrying a duct-taped notebook she found by accident. It was written by Luke Hadley, an invisible, watchful teenager who lived through the first days by noticing what everyone stronger than him missed, and who filled its pages with rules for staying alive. Following those rules across a ruined America, Nicole retraces ground Luke walked a decade and a half earlier and falls in love with a boy she is certain is long dead. Behind her, word spreads. A pilgrimage forms. And a crowd that size makes exactly the kind of noise the dark has been listening for.",
        "image": "/images/losers-guide/losers-guide-hero.webp",
        "hero_source": "/images/losers-guide/losers_guide.jpeg",
        "subtitle": "The apocalypse didn’t need a hero. It needed someone who was paying attention.",
        "teaser": "Survival of the fittest no longer applied.",
        "teaser_speaker": "Luke Hadley",
        "themes": ["Loneliness", "Connection", "The Stories We Leave Behind", "Who Actually Survives"],
        "tone": "Darkly funny. Genuinely frightening. Unexpectedly tender.",
        "comps": "The Last of Us meets Zombieland",
        "nominations": [],
        "show_gallery": False,
        "gallery": [],
        "active": True, "slate": False, "featured": False,
    },
    {
        "slug": "nowhere-kings",
        "title": "The Nowhere Kings",
        "format": "feature", "genre": "Feature — Coming-of-Age / Crime / Adventure",
        "status": "Early Development",
        "zinger": "Five small-town kids find a mysterious suitcase tied to the D.B. Cooper ransom—and set out to claim it before the world closes in.",
        "overview": "In the forgotten town of Nowhere, Oklahoma, a group of restless teenagers stumble upon a locked suitcase bearing the name “Cooper.” Inside is a map pointing to what they believe is part of the infamous D.B. Cooper ransom. Hungry for escape—from grief, poverty, and the futures laid out for them—they set off on a reckless journey to find the money and buy their way out of Nowhere. But they’re not the only ones looking. A desperate ex-FBI agent, a local deputy with ties to one of the kids, and the threat of real violence begin to close in as the group ventures deeper into the wilderness. What starts as an adventure turns into a test of loyalty, identity, and survival. By the time the truth behind the suitcase reveals itself, the kids are forced to confront a brutal reality: getting out isn’t as simple as finding the money.",
        "image": "/images/nowhere/nowhere-kings-hero.webp",
        "hero_source": "/images/nowhere/nowhere_kings.jpeg",
        "subtitle": "The summer you try to escape your life is the one that defines it.",
        "teaser": "We were kids—secretly dyin’ to grow up and too dumb to know how great we had it.",
        "teaser_speaker": "Ezra Seckinger",
        "themes": ["Identity", "Friendship", "Escape", "Loss"],
        "tone": "Nostalgic. Gritty. Funny until it’s not.",
        "comps": "Stand by Me meets No Country for Old Men",
        "nominations": [],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/nowhere/daily.webp"},
            {"src": "/images/nowhere/trouble.webp"},
        ],
        "active": True, "slate": False, "featured": False,
    },
    {
        "slug": "gas-boys",
        "title": "Gas Boyz",
        "format": "short", "genre": "Animated Short — Sci-Fi / Coming-of-Age / Comedy",
        "status": "In Production",
        "zinger": "They were just hustling snacks—until the future showed up and started taking people.",
        "overview": "In a near-future small town, three teenage hustlers run analog scams out of a dying gas station, selling small pieces of control in a world run by machines. When a fully automated AI megastore opens across the street, their way of life disappears overnight. But things turn darker when one of their own is taken and returned… different—obedient, hollow, no longer herself. Desperate to get her back, they join forces with the station’s owner, a man who’s already lost everything to the system once before. As they push deeper into the store’s core, they uncover a truth far worse than competition—this isn’t about replacing people. It’s about rewriting them.",
        "image": "/images/gas-boys/gas-boys.webp",
        "subtitle": "If you let the world think for you, it won’t stop there—it’ll decide who you are.",
        "teaser": "Think about it—no one tellin’ you what to do. You’re in control.",
        "teaser_speaker": "Dez",
        "themes": ["Identity", "Control Vs. Convenience", "Friendship", "Humanity"],
        "tone": "Offbeat. Fast-paced. Gritty. Darkly funny.",
        "comps": "Spider-Man: Into the Spider-Verse meets The Mitchells vs. the Machines",
        "nominations": [],
        "show_gallery": False,
        "gallery": [
            {"src": "/images/gas-boys/khans.webp"},
            {"src": "/images/gas-boys/wall-ees.webp"},
            {"src": "/images/gas-boys/khan.webp"},
            {"src": "/images/gas-boys/chillin.webp"},
            {"src": "/images/gas-boys/nina.webp"},
            {"src": "/images/gas-boys/wired.webp"},
            {"src": "/images/gas-boys/destroyed.webp"},
        ],
        "active": False, "slate": False, "featured": False,
    },
    {
        "slug": "the-white-raven",
        "title": "The White Raven",
        "format": "feature", "genre": "Feature — Sci-Fi Adventure / Coming-of-Age / Thriller",
        "status": "Early Development",
        "zinger": "A teenage boy discovers he can alter time—just as a ruthless agency hunts him for it.",
        "overview": "After a violent seizure fractures his reality, a teenage boy begins slipping between timelines—witnessing moments that shouldn’t be his and waking up to a life that keeps changing. When he learns he’s one of the rare few capable of altering history, he becomes the target of a covert government agency determined to control that power. Forced to run, he teams up with a group who understand the truth behind what he’s becoming—and the danger that comes with it. As timelines shift and identities unravel, he’s pushed to the edge of who he is and who he could become. Because changing the past doesn’t just rewrite history—it erases it.",
        "image": "/images/white-raven/white-raven.webp",
        "subtitle": "If you can change the past, you risk losing everything that made you who you are.",
        "teaser": "You can’t change the past. What’s done is done.",
        "teaser_speaker": "Karen Sanchez",
        "themes": ["Identity", "Control", "Fate Vs. Free Will", "Altered Reality"],
        "tone": "Fast-paced. Suspenseful. Emotional. High-concept.",
        "comps": "Chronicle meets Stranger Things",
        "nominations": [],
        "show_gallery": False,
        "gallery": [],
        "active": False, "slate": False, "featured": False,
    },
]

# Order for the homepage "slate" preview + work page grouping
FORMAT_LABEL = {"feature": "Features", "tv": "Television", "short": "Shorts"}
STATUS_GROUPS = [
    ("Produced & In Production", ["Post-Production", "In Production"]),
    ("In Development", ["In Development"]),
    ("Early / Concept", ["Early Development", "Concept"]),
]

RECOGNITION = [
    "The Black List",
    "Austin Film Festival",
    "Script Pipeline",
    "Final Draft Big Break",
    "PAGE Awards",
    "Nashville Film Festival",
    "HollyShorts Film Festival",
]

# Festivals listed by name in the Recognition block on a project page. Every
# placement still counts toward the nomination badge on thumbnails - this list
# only controls what is spelled out. Edit freely.
TIER1_ORGS = [
    "The Black List",
    "Austin Film Festival",
    "Script Pipeline",
    "Final Draft Big Break",
    "PAGE International Screenwriting Awards",
    "Nashville Film Festival",
    "HollyShorts Film Festival",
]

# Chips show the festival's common name; the full name in "org" is what goes
# into the page's structured data. Anything missing here falls back to the full
# name, so a new festival needs an entry only if its full name runs long.
ORG_SHORT = {
    "HollyShorts Film Festival": "HollyShorts",
    "Nashville Film Festival": "Nashville",
    "Austin Film Festival": "Austin",
    "Final Draft Big Break": "Big Break",
    "PAGE International Screenwriting Awards": "PAGE",
    "Los Angeles International Screenwriting Awards": "LA Screenwriting Awards",
    "Filmmatic Drama Screenplay Awards": "Filmmatic",
    "Outstanding Screenplays TV Pilot Competition": "Outstanding Screenplays",
    "PAGE International Screenwriting Awards": "PAGE",
    "Filmmatic Filmmaker Awards": "Filmmatic",
    "The Black List": "Black List",
}

PRESS_QUOTE = {
    "text": "An existential grittiness… that could satisfy the same audience drawn to Nic Pizzolatto’s work.",
    "source": "The Black List",
}
